class Translator:
    def __init__(self):
        self.current_lang = "zh"
        self.translations = {
            "zh": {
                "window_title": "Audio Books Maker",
                "tab_main": "主界面",
                "tab_settings": "设置",
                "title_label": "电子书转有声书",
                "select_files": "选择文件",
                "select_files_btn": "选择电子书",
                "selected_files_label": "已选文件:",
                "no_files_selected": "未选择文件",
                "voice_label": "语音",
                "rate_label": "语速",
                "pitch_label": "音调",
                "output_label": "输出目录",
                "output_btn": "选择文件夹",
                "merge_checkbox": "合并为单个MP3",
                "start_btn": "开始转换",
                "stop_btn": "停止",
                "status_ready": "就绪",
                "status_processing": "处理中...",
                "status_complete": "转换完成!",
                "status_error": "错误: ",
                "status_preview_generating": "正在生成试听...",
                "status_preview_failed": "试听失败: ",
                "settings_theme": "主题",
                "theme_dark": "深色",
                "theme_light": "浅色",
                "settings_language": "语言",
                "language_english": "English",
                "language_chinese": "中文",
                "settings_about": "关于",
                "about_description": "使用 Microsoft Edge TTS 将电子书转换为有声书",
                "about_author": "作者: zengkai001@qq.com",
                "about_version": "版本",
                "preview_btn": "试听",
                "log_panel": "日志",
                "show_log": "显示日志",
                "hide_log": "隐藏日志",
                "chapter_progress": "章节 {current}/{total}",
                "file_progress": "文件 {current}/{total}",
                "select_output_first": "请先选择输出目录",
                "select_files_first": "请先选择电子书文件",
                "no_ffmpeg": "未找到 ffmpeg，无法合并音频",
                "progress_connecting": "连接中...",
                "progress_fetching": "获取信息...",
                "progress_processing": "处理中...",
                "progress_completing": "完成中...",
                "error_fetch_first": "请先获取视频信息",
                "error_no_url": "请输入URL",
                "folder_btn": "选择输出文件夹",
                "status_reading": "读取文件: {filename}",
                "status_converting": "转换 {filename} - 第 {chapter}/{total} 章",
                "status_merging": "合并MP3文件...",
                "preview_text": "欢迎使用老曾的电子书工具集。",
            },
            "en": {
                "window_title": "Audio Books Maker",
                "tab_main": "Main",
                "tab_settings": "Settings",
                "title_label": "Ebook to Audiobook",
                "select_files": "Select Files",
                "select_files_btn": "Select Ebooks",
                "selected_files_label": "Selected:",
                "no_files_selected": "No files selected",
                "voice_label": "Voice",
                "rate_label": "Rate",
                "pitch_label": "Pitch",
                "output_label": "Output Folder",
                "output_btn": "Select Folder",
                "merge_checkbox": "Merge to single MP3",
                "start_btn": "Start Conversion",
                "stop_btn": "Stop",
                "status_ready": "Ready",
                "status_processing": "Processing...",
                "status_complete": "Conversion complete!",
                "status_error": "Error: ",
                "status_preview_generating": "Generating preview...",
                "status_preview_failed": "Preview failed: ",
                "settings_theme": "Theme",
                "theme_dark": "Dark",
                "theme_light": "Light",
                "settings_language": "Language",
                "language_english": "English",
                "language_chinese": "中文",
                "settings_about": "About",
                "about_description": "Convert ebooks to audiobooks using Microsoft Edge TTS",
                "about_author": "Author: zengkai001@qq.com",
                "about_version": "Version",
                "preview_btn": "Preview",
                "log_panel": "Log",
                "show_log": "Show Log",
                "hide_log": "Hide Log",
                "chapter_progress": "Chapter {current}/{total}",
                "file_progress": "File {current}/{total}",
                "select_output_first": "Please select output folder first",
                "select_files_first": "Please select ebook files first",
                "no_ffmpeg": "ffmpeg not found, cannot merge audio",
                "progress_connecting": "Connecting...",
                "progress_fetching": "Fetching info...",
                "progress_processing": "Processing...",
                "progress_completing": "Completing...",
                "error_fetch_first": "Please fetch video info first",
                "error_no_url": "Please enter URL",
                "folder_btn": "Select output folder",
                "status_reading": "Reading: {filename}",
                "status_converting": "Converting {filename} - Chapter {chapter}/{total}",
                "status_merging": "Merging MP3 files...",
                "preview_text": "Welcome to the ebook toolset.",
            }
        }

    def get(self, key):
        return self.translations.get(self.current_lang, {}).get(key, key)

    def set_language(self, lang_code):
        if lang_code in self.translations:
            self.current_lang = lang_code
            return True
        return False


translator = Translator()